# Spring Boot configuration
spring:

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/batchdb
    username: batchdb
    password: batchdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:/org/springframework/batch/core/schema-postgresql.sql
    job:
      enabled: true  # Habilita ou desabilita a execução automática de jobs
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    template:
      default-topic: produtos

server:
  port: 8080

variaveis_ambiente:
  arquivos_esperando_processamento: "arquivos-esperando-processamento"
